import type { Metadata } from "next";
import CustomMantineProvider from "./providers/CustomMantineProvider";
import CustomQueryProvider from "./providers/CustomQueryProvider";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CustomQueryProvider>
          <CustomMantineProvider>
            {children} <ToastContainer />
          </CustomMantineProvider>
        </CustomQueryProvider>
      </body>
    </html>
  );
}
